window.NR_SCHEDULE = [
  {
    "id": "schedule-nummirock-ensemble",
    "eventDate": "2026-06-17",
    "dayOrder": 0,
    "dayFi": "Keskiviikko",
    "dayEn": "Wednesday",
    "displayDate": "17.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "20:30",
    "endTime": "21:30",
    "sortMinutes": 1230,
    "endSortMinutes": 1290,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Nummirock Ensemble",
    "type": "band"
  },
  {
    "id": "schedule-suotana",
    "eventDate": "2026-06-17",
    "dayOrder": 0,
    "dayFi": "Keskiviikko",
    "dayEn": "Wednesday",
    "displayDate": "17.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "21:30",
    "endTime": "22:30",
    "sortMinutes": 1290,
    "endSortMinutes": 1350,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Suotana",
    "type": "band"
  },
  {
    "id": "schedule-riasa",
    "eventDate": "2026-06-17",
    "dayOrder": 0,
    "dayFi": "Keskiviikko",
    "dayEn": "Wednesday",
    "displayDate": "17.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "22:30",
    "endTime": "23:30",
    "sortMinutes": 1350,
    "endSortMinutes": 1410,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Riasa",
    "type": "band"
  },
  {
    "id": "schedule-ruoska",
    "eventDate": "2026-06-17",
    "dayOrder": 0,
    "dayFi": "Keskiviikko",
    "dayEn": "Wednesday",
    "displayDate": "17.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "23:30",
    "endTime": "00:30",
    "sortMinutes": 1410,
    "endSortMinutes": 1470,
    "afterMidnight": false,
    "endAfterMidnight": true,
    "name": "Ruoska",
    "type": "band"
  },
  {
    "id": "schedule-vermilia",
    "eventDate": "2026-06-17",
    "dayOrder": 0,
    "dayFi": "Keskiviikko",
    "dayEn": "Wednesday",
    "displayDate": "17.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "00:30",
    "endTime": "01:30",
    "sortMinutes": 1470,
    "endSortMinutes": 1530,
    "afterMidnight": true,
    "endAfterMidnight": true,
    "name": "Vermilia",
    "type": "band"
  },
  {
    "id": "schedule-barathrum",
    "eventDate": "2026-06-17",
    "dayOrder": 0,
    "dayFi": "Keskiviikko",
    "dayEn": "Wednesday",
    "displayDate": "17.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "01:30",
    "endTime": "02:30",
    "sortMinutes": 1530,
    "endSortMinutes": 1590,
    "afterMidnight": true,
    "endAfterMidnight": true,
    "name": "Barathrum",
    "type": "band"
  },
  {
    "id": "schedule-and-oceans",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "14:30",
    "endTime": "15:30",
    "sortMinutes": 870,
    "endSortMinutes": 930,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "And Oceans",
    "type": "band"
  },
  {
    "id": "schedule-thyrargo",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "15:30",
    "endTime": "16:30",
    "sortMinutes": 930,
    "endSortMinutes": 990,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Thyrargo",
    "type": "band"
  },
  {
    "id": "schedule-deathbyromy",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "16:30",
    "endTime": "17:30",
    "sortMinutes": 990,
    "endSortMinutes": 1050,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Death by Romy",
    "type": "band"
  },
  {
    "id": "schedule-grave",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "17:30",
    "endTime": "18:30",
    "sortMinutes": 1050,
    "endSortMinutes": 1110,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Grave",
    "type": "band"
  },
  {
    "id": "schedule-slow-fall",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "18:30",
    "endTime": "19:30",
    "sortMinutes": 1110,
    "endSortMinutes": 1170,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Slow Fall",
    "type": "band"
  },
  {
    "id": "schedule-asagraum",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "19:00",
    "endTime": "20:00",
    "sortMinutes": 1140,
    "endSortMinutes": 1200,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Asagraum",
    "type": "band"
  },
  {
    "id": "schedule-vahinkolapsi",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "19:45",
    "endTime": "20:45",
    "sortMinutes": 1185,
    "endSortMinutes": 1245,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Vahinkolapsi",
    "type": "band"
  },
  {
    "id": "schedule-swallow-the-sun",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "20:30",
    "endTime": "21:30",
    "sortMinutes": 1230,
    "endSortMinutes": 1290,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Swallow the Sun",
    "type": "band"
  },
  {
    "id": "schedule-kneel-before-the-death",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "21:30",
    "endTime": "22:30",
    "sortMinutes": 1290,
    "endSortMinutes": 1350,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Kneel Before The Death",
    "type": "band"
  },
  {
    "id": "schedule-gaerea",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "22:15",
    "endTime": "23:15",
    "sortMinutes": 1335,
    "endSortMinutes": 1395,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Gaerea",
    "type": "band"
  },
  {
    "id": "schedule-ikina",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "23:00",
    "endTime": "24:00",
    "sortMinutes": 1380,
    "endSortMinutes": 1440,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Ikinä",
    "type": "band"
  },
  {
    "id": "schedule-satyricon",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "23:45",
    "endTime": "01:00",
    "sortMinutes": 1425,
    "endSortMinutes": 1500,
    "afterMidnight": false,
    "endAfterMidnight": true,
    "name": "Satyricon",
    "type": "band"
  },
  {
    "id": "schedule-wolfheart",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "01:00",
    "endTime": "02:00",
    "sortMinutes": 1500,
    "endSortMinutes": 1560,
    "afterMidnight": true,
    "endAfterMidnight": true,
    "name": "Wolfheart",
    "type": "band"
  },
  {
    "id": "schedule-tgsobtk",
    "eventDate": "2026-06-18",
    "dayOrder": 1,
    "dayFi": "Torstai",
    "dayEn": "Thursday",
    "displayDate": "18.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "02:00",
    "endTime": "03:00",
    "sortMinutes": 1560,
    "endSortMinutes": 1620,
    "afterMidnight": true,
    "endAfterMidnight": true,
    "name": "The Great Southern Ostrobothnian Trendkillers",
    "type": "band"
  },
  {
    "id": "schedule-rockjooga",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "12:00",
    "endTime": "12:30",
    "sortMinutes": 720,
    "endSortMinutes": 750,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "RockJooga",
    "type": "activity"
  },
  {
    "id": "schedule-krabelibingo",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "12:45",
    "endTime": "13:30",
    "sortMinutes": 765,
    "endSortMinutes": 810,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Krabelibingo",
    "type": "activity"
  },
  {
    "id": "schedule-stoned-statues",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "13:30",
    "endTime": "14:30",
    "sortMinutes": 810,
    "endSortMinutes": 870,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Stoned Statues",
    "type": "band"
  },
  {
    "id": "schedule-omnium-gatherum",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "14:30",
    "endTime": "15:30",
    "sortMinutes": 870,
    "endSortMinutes": 930,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Omnium Gatherum",
    "type": "band"
  },
  {
    "id": "schedule-inborn-tendency",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "15:30",
    "endTime": "16:30",
    "sortMinutes": 930,
    "endSortMinutes": 990,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Inborn Tendency",
    "type": "band"
  },
  {
    "id": "schedule-immortal-disfigurement",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "16:00",
    "endTime": "17:00",
    "sortMinutes": 960,
    "endSortMinutes": 1020,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Immortal Disfigurement",
    "type": "band"
  },
  {
    "id": "schedule-plaguebreeder",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "17:00",
    "endTime": "18:00",
    "sortMinutes": 1020,
    "endSortMinutes": 1080,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Plaguebreeder",
    "type": "band"
  },
  {
    "id": "schedule-moonsorrow",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "17:30",
    "endTime": "18:45",
    "sortMinutes": 1050,
    "endSortMinutes": 1125,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Moonsorrow",
    "type": "band"
  },
  {
    "id": "schedule-eartheria",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "18:45",
    "endTime": "19:45",
    "sortMinutes": 1125,
    "endSortMinutes": 1185,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Eartheria",
    "type": "band"
  },
  {
    "id": "schedule-decessus",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "19:15",
    "endTime": "20:15",
    "sortMinutes": 1155,
    "endSortMinutes": 1215,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Decessus",
    "type": "band"
  },
  {
    "id": "schedule-noiduin",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "20:00",
    "endTime": "21:00",
    "sortMinutes": 1200,
    "endSortMinutes": 1260,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Noiduin",
    "type": "band"
  },
  {
    "id": "schedule-stam1na",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "20:30",
    "endTime": "21:45",
    "sortMinutes": 1230,
    "endSortMinutes": 1305,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Stam1na",
    "type": "band"
  },
  {
    "id": "schedule-hanging-garden",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "21:45",
    "endTime": "22:45",
    "sortMinutes": 1305,
    "endSortMinutes": 1365,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Hanging Garden",
    "type": "band"
  },
  {
    "id": "schedule-kaunis-kuolematon",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "22:30",
    "endTime": "23:30",
    "sortMinutes": 1350,
    "endSortMinutes": 1410,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Kaunis Kuolematon",
    "type": "band"
  },
  {
    "id": "schedule-sepulchral-curse",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "23:15",
    "endTime": "00:15",
    "sortMinutes": 1395,
    "endSortMinutes": 1455,
    "afterMidnight": false,
    "endAfterMidnight": true,
    "name": "Sepulchral Curse",
    "type": "band"
  },
  {
    "id": "schedule-black-veil-brides",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "24:00",
    "endTime": "01:15",
    "sortMinutes": 1440,
    "endSortMinutes": 1515,
    "afterMidnight": false,
    "endAfterMidnight": true,
    "name": "Black Veil Brides",
    "type": "band"
  },
  {
    "id": "schedule-pikakassa",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "01:15",
    "endTime": "02:15",
    "sortMinutes": 1515,
    "endSortMinutes": 1575,
    "afterMidnight": true,
    "endAfterMidnight": true,
    "name": "Pikakassa",
    "type": "band"
  },
  {
    "id": "schedule-emo-disco",
    "eventDate": "2026-06-19",
    "dayOrder": 2,
    "dayFi": "Perjantai",
    "dayEn": "Friday",
    "displayDate": "19.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "02:00",
    "endTime": "03:00",
    "sortMinutes": 1560,
    "endSortMinutes": 1620,
    "afterMidnight": true,
    "endAfterMidnight": true,
    "name": "Emodisko",
    "type": "band"
  },
  {
    "id": "schedule-rockjooga-2",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "12:00",
    "endTime": "12:45",
    "sortMinutes": 720,
    "endSortMinutes": 765,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "RockJooga",
    "type": "activity"
  },
  {
    "id": "schedule-kalevauva",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "12:45",
    "endTime": "13:30",
    "sortMinutes": 765,
    "endSortMinutes": 810,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Kalevauva",
    "type": "band"
  },
  {
    "id": "schedule-boycott",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "13:30",
    "endTime": "14:30",
    "sortMinutes": 810,
    "endSortMinutes": 870,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Boycott",
    "type": "band"
  },
  {
    "id": "schedule-elakelaiset",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "14:30",
    "endTime": "15:30",
    "sortMinutes": 870,
    "endSortMinutes": 930,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Eläkeläiset",
    "type": "band"
  },
  {
    "id": "schedule-saa-kiljua",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "15:30",
    "endTime": "16:15",
    "sortMinutes": 930,
    "endSortMinutes": 975,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Saa Kiljua",
    "type": "band"
  },
  {
    "id": "schedule-nyrkkitappelu",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "16:15",
    "endTime": "17:15",
    "sortMinutes": 975,
    "endSortMinutes": 1035,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Nyrkkitappelu",
    "type": "band"
  },
  {
    "id": "schedule-timo-rautiainen",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "17:15",
    "endTime": "18:15",
    "sortMinutes": 1035,
    "endSortMinutes": 1095,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Timo Rautiainen ja Trio Niskalaukaus",
    "type": "band"
  },
  {
    "id": "schedule-burlesque",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "18:30",
    "endTime": "19:00",
    "sortMinutes": 1110,
    "endSortMinutes": 1140,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Burlesque",
    "type": "performer"
  },
  {
    "id": "schedule-rise-of-the-northstar",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "19:00",
    "endTime": "20:00",
    "sortMinutes": 1140,
    "endSortMinutes": 1200,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Rise of the Northstar",
    "type": "band"
  },
  {
    "id": "schedule-psycho-bats",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "19:00",
    "endTime": "20:00",
    "sortMinutes": 1140,
    "endSortMinutes": 1200,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Psycho Bats",
    "type": "band"
  },
  {
    "id": "schedule-burlesque-2",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "20:00",
    "endTime": "20:45",
    "sortMinutes": 1200,
    "endSortMinutes": 1245,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Burlesque",
    "type": "performer"
  },
  {
    "id": "schedule-gloryhammer",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "20:15",
    "endTime": "21:30",
    "sortMinutes": 1215,
    "endSortMinutes": 1290,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Gloryhammer",
    "type": "band"
  },
  {
    "id": "schedule-paara",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "21:30",
    "endTime": "22:15",
    "sortMinutes": 1290,
    "endSortMinutes": 1335,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Paara",
    "type": "band"
  },
  {
    "id": "schedule-lost-society",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 1,
    "stageName": "Inferno Stage",
    "startTime": "22:00",
    "endTime": "23:00",
    "sortMinutes": 1320,
    "endSortMinutes": 1380,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Lost Society",
    "type": "band"
  },
  {
    "id": "schedule-awake-again",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "23:00",
    "endTime": "24:00",
    "sortMinutes": 1380,
    "endSortMinutes": 1440,
    "afterMidnight": false,
    "endAfterMidnight": false,
    "name": "Awake Again",
    "type": "band"
  },
  {
    "id": "schedule-battle-beast",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 0,
    "stageName": "Main Stage",
    "startTime": "24:00",
    "endTime": "01:15",
    "sortMinutes": 1440,
    "endSortMinutes": 1515,
    "afterMidnight": false,
    "endAfterMidnight": true,
    "name": "Battle Beast",
    "type": "band"
  },
  {
    "id": "schedule-stereo-terror",
    "eventDate": "2026-06-20",
    "dayOrder": 3,
    "dayFi": "Lauantai",
    "dayEn": "Saturday",
    "displayDate": "20.6.",
    "stageOrder": 2,
    "stageName": "Kaaos Klubi",
    "startTime": "01:15",
    "endTime": "04:00",
    "sortMinutes": 1515,
    "endSortMinutes": 1680,
    "afterMidnight": true,
    "endAfterMidnight": true,
    "name": "Stereo Terror",
    "type": "band"
  }
];
